### ISSUE TITLE
Does not show output/draw on modified Ender 3?

### ISSUE THREAD

**Issue by Hukuma1** [npiegdon/bed-inspector#4] opened 2019-12-27 01:38 UTC
First off, thank you for making this! I saw your video on you (physically) fixing your bed and writing this utility. Amazing work.

I am running an Ender 3 with the Bigtreetech SKR E3 Mini v1.2 with BL Touch running latest Marlin v2.01 and the printer connects and I can click around, but I get nothing echo'd back to the text area and nothing is being drawn onto the grid. Just big black screen. I do have extra probing (probes 4 total times to get more accurate average) setup in Marlin and I wonder if that is the issue?

**Comment by GokuWorks** [comment] 2019-12-29 18:52
Same here with SKR v1.3

**Comment by npiegdon** [comment] 2019-12-29 21:01
It's hard to diagnose this sort of thing without access to the printer.

When you say "I can click around", do you mean that the app is able to move the print head on your printer?  That at least confirms that the serial port settings are (mostly?) correct.

If either of you could, please check the Marlin documentation for their supported G-Code.  My PrintrBot uses a many-years-old version of Marlin and I wonder if they changed which code does the diagnostic output between then and now.  You should be able to poke at the printer in any serial port app or even in the advanced print dialog boxes of most slicers.

If you can find any single command that will get the measurements off the probe, it should be easy to incorporate that into this app.

**Comment by Hukuma1** [comment] 2019-12-29 21:07
> When you say "I can click around", do you mean that the app is able to move the print head on your printer? That at least confirms that the serial port settings are (mostly?) correct.
> 

Correct. It definitely has a connection to the printer and I can move it/probe.

What's the old G command you're using? Maybe we can see if it got deprecated/replaced with another code? There is also Marlin G29 debug mode (which is disabled by default due to romsize limitations). Does your program use that perhaps?

I'm using Pronterface and can issue any command to the printer. Let me know and I'd love to help you add support for this printer.

**Comment by npiegdon** [comment] 2019-12-29 22:50
If you search [BedLeveler.cs](https://github.com/npiegdon/bed-inspector/blob/master/BedLeveler.cs) for `.Send(`, all the G-code is scattered across that file.  The measurements are taken with G30.  At least on my PrintrBot Simple Metal's firmware, that checks the z-probe height and sends it back to the app via the serial port.

Once we know the right commands for different printers, it shouldn't take too much effort to pull those G-codes out into a settings menu to make it user-adjustable.

Something already on the to-do list is to parse the response with a user-editable RegEx so it can support more than the currently hard-coded `Bed Position X: 13.00 Y: 10.00 Z: 0.10` type of string that my own printer returns.

**Comment by Hukuma1** [comment] 2019-12-30 01:01
Looks like G30 is still the same: Single Z-Probe

http://marlinfw.org/docs/gcode/G030.html

Did the syntax change?

**Comment by Hukuma1** [comment] 2019-12-30 01:33
Just had a chance to try it in Pronterface:

>>> G1 X200 Y200
SENDING:G1 X200 Y200
>>> G30
SENDING:G30
Bed X: 156.00 Y: 186.00 Z: -0.31

So it seems to work (even with multiple probes option enabled). Seems like it's simply a display issue?

**Comment by npiegdon** [comment] 2020-01-03 10:18
Hmm, the only thing that should be [filtered out](https://github.com/npiegdon/bed-inspector/blob/master/BedLeveler.cs#L85) of that view completely are the short "ok" acknowledgement messages that get sent back after a command (presumably to confirm it was parsed successfully).

Just a couple [lines later](https://github.com/npiegdon/bed-inspector/blob/master/BedLeveler.cs#L93), I could see why it would skip processing the response from your printer (it starts with "Bed" instead of "Bed Position"; which would be fixed by that RegEx feature I mentioned earlier) but the text should always appear in the sidebar, even if the app doesn't recognize it.

Are you able to see the serial port settings that Pronterface uses?  I wonder if there is something still preventing your printer's text from making it through successfully?

The (hard-coded [for now](https://github.com/npiegdon/bed-inspector/blob/master/PrinterPort.cs#L21)) settings for the serial port are:
- Speed: 115200
- Parity: None
- Data bits: 8
- Stop bits: 1
- Handshake: None

Searching around for Marlin serial port settings, it looks like 250000bps might be a newer/better speed setting.  At least [this report](https://reprap.org/forum/read.php?267,649673) mentions that 115200 didn't work.  Exposing those settings in the app sooner rather than later might be a good idea.

**Comment by Hukuma1** [comment] 2020-01-04 18:11
Using default settings of 115200 in Pronterface and connects/works as expected. I also have those baud rates set in Marlin firmware as well.

Any chance it's simply a display bug of MS Net libraries or anything? Running latest Win10.

**Comment by ipatch** [comment] 2020-01-16 21:09
@Hukuma1 

I'm experiencing the exact same behavior from the app that you're describing, I recorded a video of the issue, and I'll link to it here in a few.

**Comment by npiegdon** [comment] 2020-01-22 01:48
@Hukuma1 
Looking at the code again, it doesn't look like there is any chance it's just a display issue in the text box.  It's very strange that all of the connection settings are exactly the same but communication seems to only be happening in one direction!

I'd be curious to see if any of the other .NET SerialPort properties (RtsEnable and DtrEnable especially) are necessary.  I just poked through the Pronterface source (which uses pySerial) and you're right: the settings match right down the line, except it looks like Pronterface does try to set the equivalent of DtrEnable under some circumstances.  That's my only lead at the moment.  Everything else looks identical.

@ipatch 
Wow, that was very thorough!  (I'm sorry you had to go through all that troubleshooting.)

The "Set Z = 5.0mm" button is describing an action.  That is, "Change the print head's Z coordinate to 5.0mm from the print bed by sending a 'G1 Z5 F6000' command".

I couldn't tell exactly from the video (the printer wasn't in-frame when you clicked in the black area), to see whether it was actually moving the head down until the probe picked something up.  The G30 that is sent when clicking the bed is supposed to take a "single Z probe" measurement, so if the printer isn't moving in the Z direction when clicking in the black area, this might be something different.  (The "Set Z = 5.0mm" button is just a quick utility to get the print head a little further away from the bed.)

**Comment by ipatch** [comment] 2020-01-22 01:59
@npiegdon 

thanks for coming back to the party 🎉🙏

uhhh, i actually setup another VM _Windows 7_ just to make sure it wasn't a Windows 10 / 7 thing, and got exactly the same results with Windows 7 as I did with Windows 10.

When I click the _Connect_ button the _bed-leveler_ app connects to my printer ie. a SKR v1.3 board, and then precedes to home the printer which works as intended.  I then adjust the bed size to fit the bed size for my particular printer.

I then click on a black spot within the black box ⬛️ the printer then begins to probe the spot that i clicked with my mouse, and lowers the print head to the bed until the probe _inductive sensor for me_ detects the bed, then sends the print head back up on the z axis, but I never see a colored circle within the black box appear, nor do I see any text _gcode commands_ appear in the text area of the app.

I far from having any csharp or visual studio code experience, but I had some time today to comb through a couple of visual studio docs on the microsoft website, and time permitting tomorrow I'll try and step through the program using <kbd>f11</kbd> to see what I can figure out.

I think you kind of hinted at what is going on here, in that the _responses_ coming back from the printer and not being properly _parsed_ (_and I use that term loosely_) because I'm not seeing any output in the area below the connect button.  Hopefully, I have something a little more tangible in a day or two, time permitting of course.

...also awesome youtube video, and the app looks awesome too, can't wait to get it to work, and I'd love to get to run on a rpi using .net core so i could run it on the rpi connected to my printer.

**Comment by npiegdon** [comment] 2020-01-22 03:48
Alright, if the head is lowered until the probe detects, then it sounds like every report of this problem is identical.  (I suppose that's a good thing.)

Debugging the app would be very helpful!  After a bit of digging, I learned that .NET's built-in SerialPort API is... [not great](http://www.sparxeng.com/blog/software/must-use-net-system-io-ports-serialport).  I just did some tinkering to address the problems described in that article.  Maybe that fixed something.  If you grab the latest from GitHub and run it from Visual Studio as-is, do you see any text output in the sidebar?

If not, try setting a breakpoint in PrinterPort.cs on [line 116](https://github.com/npiegdon/bed-inspector/blob/d87e082b8a729272319d76b507a8213b9da0b851/PrinterPort.cs#L116).  Assuming the little drop-down at the top of Visual Studio says "Debug" and you start the app by pressing F5, that breakpoint should hit whenever data comes in from the printer.  If it's not being hit, that means there's still a problem.

**Comment by ipatch** [comment] 2020-01-23 16:24
Not trying to beat a dead horse, but I merged in your commit yesterday and shot a short video of me using the app / utility with the commit merged and I'm now seeing output in the text area.

https://www.youtube.com/watch?v=ihCSoqvvR54

**Comment by npiegdon** [comment] 2020-01-23 19:33
Woo hoo!  Getting the text to display is the hard part!  It looks like you've got a good serial port connection now!

Getting the app to interpret the response correctly should be much easier.  In the future, I'm hoping to make this more flexible (to accommodate just about any printer), but for now it's a manual step.

What needs to change is the [BedLeveler.DataReceived](https://github.com/npiegdon/bed-inspector/blob/master/BedLeveler.cs#L93) callback.  Right now it's hard-coded to look for a response that starts with "Bed Position:", splits the string up on spaces, and then checks the 4th, 6th, and 8th token for the X, Y, and Z numbers.  That happens to work for my PrintrBot Simple Metal... but nowhere else. :/

Looking at your output in that video (thanks again! Sheesh, you're going to a lot of trouble to capture everything there!), there aren't any spaces between the coordinate name and the value (e.g., "X: 100.0" instead of your "X:100.0"), so updating the checking code won't be as easy as just changing those token indices.

The Right Thing™ would be a RegEx-based solution.  That would solve it easily for your situation and just about every other.  I'm still at work.  Give me an evening to try and get something working.

Thanks again for all of your work tracking this stuff down!

**Comment by ipatch** [comment] 2020-01-23 20:39
@npiegdon 

**wow** you're an amazing dude.  my csharp skills are abysmal, but I did read a few visual studio docs on running the app with the debugger attached, and reading your comments, i was able to hack the current source and get a little red circle with green text within the circle, i added the green text while tooling around with the source.

but once again, the above comment you left pointed me in the right direction, and being able to attach the debugger to the running app, i was able to change the values to match my response from my printer to get the app to render a nice little 🔴 circle.

super stoked. 🤙

---

and totally agree, umm having a more proper way to handle all the different responses different board would send to this utility would be ideal as you stated using a _regex_ to match / parse the different responses for different boards.

once again ...stoked.

**Comment by npiegdon** [comment] 2020-01-23 21:34
Hmm, looking again at your printer's output, it almost looks like it's reporting everything twice (or even three times?) using different coordinate systems.  (I'm guessing "Counts" has to do with the number of steps each stepper motor has made.)

But the first one seems to start with "Bed" so all the modifications you made in that screenshot ("Bed" instead of "Bed Position"; "Length != 7" instead of 8; and 2/4/6 for the token indices instead of 3/5/7) seem like they should be enough to get things working.  If you remove that breakpoint and just click around, that doesn't create the appropriate circles wherever you click?

It looks like the only instruction that doesn't return all three sets of values is the initial G28+G30 pair to home and measure the center.  Hmm.

**Comment by ipatch** [comment] 2020-01-23 21:36
<img width="1748" alt="Screen Shot 2020-01-23 at 3 35 23 PM" src="https://user-images.githubusercontent.com/613805/73025913-131ae400-3df6-11ea-95d7-66f2efde74eb.png">

**Comment by npiegdon** [comment] 2020-01-23 21:45
Congratulations!  That's awesome!  That's also a lot of clicking.  This is where the "Measure every" tool comes in handy. hehe.

I think I'll try to get a simple regex feature added (maybe another tab in addition to "Bed Size" and "Colors") and push out a release.  That should make it easier for the other two people that reported this issue to test it.

**Comment by ipatch** [comment] 2020-01-23 22:00
> EDIT: Also, while it looks like your bed needs some corner-to-corner adjustment, it appears to actually be flat.

yeah totally, i think the issue with my bed is how it's mounted in the printer.

and i'm sure i'm not the only person who would like to see another official release of this app.  thanks again, for writing this.

**Comment by npiegdon** [comment] 2020-01-29 16:21
Alright, with any luck, the v1.3 release that just went up should work out of the box for all of you!  Once I hear from ~2 of you, I'll consider this closed. 😄

(In other news: I had way too much fun making the "Custom" box show the parameters in color.  Hopefully that'll help people figure out whether they're typing in something valid.)

**Comment by Hukuma1** [comment] 2020-01-29 22:05
It connects. It says stuff in the console. It draws on the screen! Yes! Thank you! :)

Is there a way to add edge offset? I have clips holding my glass bed and the last time I hit the measure corners button the nozzle crashed into them.

Also when I click on the points now, the color circle shows up in a different location than my mouse click. I assume this is due to my bed size and maybe custom bed size from Marlin config? (I have it extended so probe can read more points of the bed but the nozzle is technically off the bed)

**Comment by ipatch** [comment] 2020-01-29 23:08
@Hukuma1 

I to was noticing the issue of where i clicked within the black rectangle ◼️ the probe point _color circle_ wasn't exactly placed where i clicked in the black rectangle.

My best guess when looking at my hot end assembly was that this app puts the nozzle where clicked but you also have to count for your probe offset from your nozzle.

In my case my probe is in front and to the left of my nozzle if looking at the printer from the front. so the color circles were appearing to the left and a little _below_ where I clicked on the black rectangle.

This could be different for you however, depending on how you have your `NOZZLE_TO_PROBE_OFFSET` configured in marlin.

**Comment by npiegdon** [comment] 2020-01-30 00:46
All of that is great news!

I vaguely recall that `NOZZLE_TO_PROBE_OFFSET` thing coming up with my own printer.  I forget when/how I "fixed" it, but if I had to guess, it probably involved setting the offset to zero.

Thanks again for the feedback; I'm going to close this one for now.

If you'd like to open a new issue about either/both of the "keep out"/"border" feature as well as some counter-probe-offset mechanism, I've put those on the list for v1.4 (along with a choice of digit separator in the custom regex matching to handle comma digit separators).

**Closed by npiegdon** 2020-01-30 00:46 UTC
